;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-newline
        autopair-skip-close-maybe
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        comment-or-uncomment-region-or-line
        cut-line-or-region
        downcase-region
        electric-pair-delete-pair
        git-rebase-squash
        handle-switch-frame
        indent-for-tab-command
        keyboard-escape-quit
        markdown-outdent-or-delete
        sh-assignment
        suspend-frame
        xterm-paste
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-backward-selection
        isearch-forward-selection
        smex
        ))
